use gameboy::registers;

#[derive(Eq, PartialEq)]
pub enum Operand {
    None,
    Imm8(u8),
    Imm16(u16),
    Register(registers::Registers),
    Addr8(u8),
    Addr16(u16),
}

impl Operand {
    pub fn unwrap_imm8(&self) -> u8 {
        match *self {
            Operand::Imm8(val) => val,
            _ => panic!("Attempted to unwrap imm8 operand when it is not of type Imm8"),
        }
    }

    pub fn unwrap_imm16(&self) -> u16 {
        match *self {
            Operand::Imm16(addr) => addr,
            _ => panic!("Attempted to unwrap imm16 operand when it is not of type Imm16"),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ArgumentType {
    Implied,
    Imm8,
    Imm16,
    Register,
    Address,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OpCode {
    pub code: u8,
    pub mnemonic: &'static str,
    pub length: u16,
    pub cycles: u8,
    pub argument_type: ArgumentType,
    pub extended: bool,
}

impl OpCode {
    pub fn from_byte<'opcode>(byte: u8, extended: bool) -> Option<&'opcode OpCode> {
        if extended {
            EXT_OPCODES.iter().find(|opcode| opcode.code == byte)
        } else {
            OPCODES.iter().find(|opcode| opcode.code == byte)
        }
    }

    pub fn from_mnemonic<S>(input: S) -> Option<OpCode>
        where S: Into<String>
    {
        let input = input.into();
        OPCODES.iter()
            .find(|opcode| opcode.mnemonic == input.to_uppercase())
            .cloned()
    }
}

static OPCODES: [OpCode; 201] = [OpCode {
                                     code: 0x00,
                                     mnemonic: "NOP",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x01,
                                     mnemonic: "LD BC, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x02,
                                     mnemonic: "LD (BC), A",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x03,
                                     mnemonic: "INC BC",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x04,
                                     mnemonic: "INC B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x05,
                                     mnemonic: "DEC B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x06,
                                     mnemonic: "LD B, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x07,
                                     mnemonic: "RCLA",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x08,
                                     mnemonic: "LD ({imm16}), SP",
                                     length: 3,
                                     cycles: 20,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x09,
                                     mnemonic: "ADD HL, BC",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x0A,
                                     mnemonic: "LD A, (BC)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x0B,
                                     mnemonic: "DEC BC",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x0C,
                                     mnemonic: "INC C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x0D,
                                     mnemonic: "DEC C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x0E,
                                     mnemonic: "LD C, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x11,
                                     mnemonic: "LD DE, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x12,
                                     mnemonic: "LD (DE), A",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x13,
                                     mnemonic: "INC DE",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x14,
                                     mnemonic: "INC D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x15,
                                     mnemonic: "DEC D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x16,
                                     mnemonic: "LD D, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x17,
                                     mnemonic: "RLA",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x18,
                                     mnemonic: "JP {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x19,
                                     mnemonic: "ADD HL, DE",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x1A,
                                     mnemonic: "LD A, (DE)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x1B,
                                     mnemonic: "DEC DE",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x1C,
                                     mnemonic: "INC E",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x1D,
                                     mnemonic: "DEC E",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x1E,
                                     mnemonic: "LD E, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x1F,
                                     mnemonic: "RRA",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x20,
                                     mnemonic: "JR NZ, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x21,
                                     mnemonic: "LD HL, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x22,
                                     mnemonic: "LD (HLI), A",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x23,
                                     mnemonic: "INC HL",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x24,
                                     mnemonic: "INC H",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x25,
                                     mnemonic: "DEC H",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x26,
                                     mnemonic: "LD H, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x27,
                                     mnemonic: "DAA",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x28,
                                     mnemonic: "JR Z, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x29,
                                     mnemonic: "ADD HL, HL",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x2A,
                                     mnemonic: "LD A, (HLI)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x2B,
                                     mnemonic: "DEC HL",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x2C,
                                     mnemonic: "INC L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x2D,
                                     mnemonic: "DEC L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x2E,
                                     mnemonic: "LD L, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x2F,
                                     mnemonic: "CPL",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x30,
                                     mnemonic: "JR NC, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x31,
                                     mnemonic: "LD SP, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x32,
                                     mnemonic: "LD (HLD), A",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x33,
                                     mnemonic: "INC SP",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x34,
                                     mnemonic: "INC (HL)",
                                     length: 1,
                                     cycles: 12,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x35,
                                     mnemonic: "DEC (HL)",
                                     length: 1,
                                     cycles: 12,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x36,
                                     mnemonic: "LD (HL), {imm8}",
                                     length: 2,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x38,
                                     mnemonic: "JR C, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x39,
                                     mnemonic: "ADD HL, SP",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x3A,
                                     mnemonic: "LD A, (HLD)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x3B,
                                     mnemonic: "DEC SP",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x3C,
                                     mnemonic: "INC A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x3D,
                                     mnemonic: "DEC A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x3E,
                                     mnemonic: "LD A, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x40,
                                     mnemonic: "LD B, B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x41,
                                     mnemonic: "LD B, C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x42,
                                     mnemonic: "LD B, D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x43,
                                     mnemonic: "LD B, E",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x44,
                                     mnemonic: "LD B, H",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x45,
                                     mnemonic: "LD B, L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x46,
                                     mnemonic: "LD B, (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x47,
                                     mnemonic: "LD B, A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x48,
                                     mnemonic: "LD C, B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x49,
                                     mnemonic: "LD C, C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x4A,
                                     mnemonic: "LD C, D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x4B,
                                     mnemonic: "LD C, E",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x4C,
                                     mnemonic: "LD C, H",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x4D,
                                     mnemonic: "LD C, L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x4E,
                                     mnemonic: "LD C, (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x4F,
                                     mnemonic: "LD C, A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x50,
                                     mnemonic: "LD D, B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x51,
                                     mnemonic: "LD D, C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x52,
                                     mnemonic: "LD D, D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x53,
                                     mnemonic: "LD D, E",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x54,
                                     mnemonic: "LD D, H",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x55,
                                     mnemonic: "LD D, L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x56,
                                     mnemonic: "LD D, (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x57,
                                     mnemonic: "LD D, A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x58,
                                     mnemonic: "LD E, B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x59,
                                     mnemonic: "LD E, C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x5A,
                                     mnemonic: "LD E, D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x5B,
                                     mnemonic: "LD E, E",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x5C,
                                     mnemonic: "LD E, H",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x5D,
                                     mnemonic: "LD E, L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x5E,
                                     mnemonic: "LD E, (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x5F,
                                     mnemonic: "LD E, A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x60,
                                     mnemonic: "LD H, B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x61,
                                     mnemonic: "LD H, C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x62,
                                     mnemonic: "LD H, D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x63,
                                     mnemonic: "LD H, E",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x64,
                                     mnemonic: "LD H, H",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x65,
                                     mnemonic: "LD H, L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x66,
                                     mnemonic: "LD H, (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x67,
                                     mnemonic: "LD H, A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x68,
                                     mnemonic: "LD L, B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x69,
                                     mnemonic: "LD L, C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x6A,
                                     mnemonic: "LD L, D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x6B,
                                     mnemonic: "LD L, E",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x6C,
                                     mnemonic: "LD L, H",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x6D,
                                     mnemonic: "LD L, L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x6E,
                                     mnemonic: "LD L, (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x6F,
                                     mnemonic: "LD L, A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x70,
                                     mnemonic: "LD (HL), B",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x71,
                                     mnemonic: "LD (HL), C",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x72,
                                     mnemonic: "LD (HL), D",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x73,
                                     mnemonic: "LD (HL), E",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x74,
                                     mnemonic: "LD (HL), H",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x75,
                                     mnemonic: "LD (HL), L",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x76,
                                     mnemonic: "HALT",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x77,
                                     mnemonic: "LD (HL), A",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x78,
                                     mnemonic: "LD A, B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x79,
                                     mnemonic: "LD A, C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x7A,
                                     mnemonic: "LD A, D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x7B,
                                     mnemonic: "LD A, E",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x7C,
                                     mnemonic: "LD A, H",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x7D,
                                     mnemonic: "LD A, L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x7E,
                                     mnemonic: "LD A, (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x7F,
                                     mnemonic: "LD A, A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x80,
                                     mnemonic: "ADD A, B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x82,
                                     mnemonic: "ADD A, D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x85,
                                     mnemonic: "ADD A, L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x86,
                                     mnemonic: "ADD A, (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x87,
                                     mnemonic: "AND A, A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x89,
                                     mnemonic: "ADC A, C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x8E,
                                     mnemonic: "ADC A, (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x90,
                                     mnemonic: "SUB B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x96,
                                     mnemonic: "SUB (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x97,
                                     mnemonic: "SUB A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0x9A,
                                     mnemonic: "SBC A, D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xA1,
                                     mnemonic: "AND C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xA7,
                                     mnemonic: "AND A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xA8,
                                     mnemonic: "XOR B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xA9,
                                     mnemonic: "XOR C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xAD,
                                     mnemonic: "XOR L",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xAE,
                                     mnemonic: "XOR (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xAF,
                                     mnemonic: "XOR A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xB0,
                                     mnemonic: "OR B",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xB1,
                                     mnemonic: "OR C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xB2,
                                     mnemonic: "OR D",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xB6,
                                     mnemonic: "OR (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xB7,
                                     mnemonic: "OR A",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xB9,
                                     mnemonic: "CP C",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xBE,
                                     mnemonic: "CP (HL)",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xC0,
                                     mnemonic: "RET NZ",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xC1,
                                     mnemonic: "POP BC",
                                     length: 1,
                                     cycles: 12,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xC2,
                                     mnemonic: "JP NZ, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xC3,
                                     mnemonic: "JP {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xC4,
                                     mnemonic: "CALL NZ, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xC5,
                                     mnemonic: "PUSH BC",
                                     length: 1,
                                     cycles: 16,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xC6,
                                     mnemonic: "ADD A, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xC7,
                                     mnemonic: "RST 0x00",
                                     length: 1,
                                     cycles: 32,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xC8,
                                     mnemonic: "RET Z",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xC9,
                                     mnemonic: "RET",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xCA,
                                     mnemonic: "JP Z, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xCB,
                                     mnemonic: "",
                                     length: 1,
                                     cycles: 0,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xCC,
                                     mnemonic: "CALL Z, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xCD,
                                     mnemonic: "CALL {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xCE,
                                     mnemonic: "ADC A, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xCF,
                                     mnemonic: "RST 0x08",
                                     length: 1,
                                     cycles: 32,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xD0,
                                     mnemonic: "RET NC",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xD1,
                                     mnemonic: "POP DE",
                                     length: 1,
                                     cycles: 12,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xD2,
                                     mnemonic: "JP NC, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xD4,
                                     mnemonic: "CALL NC, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xD5,
                                     mnemonic: "PUSH DE",
                                     length: 1,
                                     cycles: 16,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xD6,
                                     mnemonic: "SUB {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xD7,
                                     mnemonic: "RST 0x10",
                                     length: 1,
                                     cycles: 32,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xD8,
                                     mnemonic: "RET C",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xD9,
                                     mnemonic: "RETI",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xDA,
                                     mnemonic: "JP C, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xDC,
                                     mnemonic: "CALL C, {imm16}",
                                     length: 3,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xDE,
                                     mnemonic: "SBC A, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xDF,
                                     mnemonic: "RST 0x18",
                                     length: 1,
                                     cycles: 32,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xE0,
                                     mnemonic: "LD ($FF00+{imm8}), A",
                                     length: 2,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xE1,
                                     mnemonic: "POP HL",
                                     length: 1,
                                     cycles: 12,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xE2,
                                     mnemonic: "LD ($FF00+C), A",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xE5,
                                     mnemonic: "PUSH HL",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xE6,
                                     mnemonic: "AND {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xE7,
                                     mnemonic: "RST 0x20",
                                     length: 1,
                                     cycles: 32,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xE8,
                                     mnemonic: "ADD SP, {imm8}",
                                     length: 2,
                                     cycles: 16,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xE9,
                                     mnemonic: "JP (HL)",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xEA,
                                     mnemonic: "LD ({imm16}), A",
                                     length: 3,
                                     cycles: 16,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xEE,
                                     mnemonic: "XOR A, {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xEF,
                                     mnemonic: "RST 0x28",
                                     length: 1,
                                     cycles: 32,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xF0,
                                     mnemonic: "LD A, ($FF00+{imm8})",
                                     length: 2,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xF1,
                                     mnemonic: "POP AF",
                                     length: 1,
                                     cycles: 12,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xF3,
                                     mnemonic: "DI",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xF5,
                                     mnemonic: "PUSH AF",
                                     length: 1,
                                     cycles: 16,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xF6,
                                     mnemonic: "OR {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xF7,
                                     mnemonic: "RST 0x30",
                                     length: 1,
                                     cycles: 32,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xF8,
                                     mnemonic: "LDHL SP, {imm8}",
                                     length: 2,
                                     cycles: 12,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xF9,
                                     mnemonic: "LD SP, HL",
                                     length: 1,
                                     cycles: 8,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xFA,
                                     mnemonic: "LD A, ({imm16})",
                                     length: 3,
                                     cycles: 16,
                                     argument_type: ArgumentType::Imm16,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xFB,
                                     mnemonic: "EI",
                                     length: 1,
                                     cycles: 4,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xFE,
                                     mnemonic: "CP {imm8}",
                                     length: 2,
                                     cycles: 8,
                                     argument_type: ArgumentType::Imm8,
                                     extended: false,
                                 },
                                 OpCode {
                                     code: 0xFF,
                                     mnemonic: "RST 0x38",
                                     length: 1,
                                     cycles: 32,
                                     argument_type: ArgumentType::Implied,
                                     extended: false,
                                 }];

// EXTENDED OPCODES (all prefixed with 0xCB)

static EXT_OPCODES: [OpCode; 35] = [OpCode {
                                        code: 0x11,
                                        mnemonic: "RL C",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x19,
                                        mnemonic: "RR C",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x1A,
                                        mnemonic: "RR D",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x1B,
                                        mnemonic: "RR E",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x27,
                                        mnemonic: "SLA A",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x33,
                                        mnemonic: "SWAP E",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x37,
                                        mnemonic: "SWAP A",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x38,
                                        mnemonic: "SRL B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Imm16,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x3F,
                                        mnemonic: "SRL A",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x40,
                                        mnemonic: "BIT 0, B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x41,
                                        mnemonic: "BIT 0, C",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x46,
                                        mnemonic: "BIT 0, (HL)",
                                        length: 1,
                                        cycles: 16,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x47,
                                        mnemonic: "BIT 0, A",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x48,
                                        mnemonic: "BIT 1, B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x50,
                                        mnemonic: "BIT 2, B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x57,
                                        mnemonic: "BIT 2, A",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x58,
                                        mnemonic: "BIT 3, B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x5F,
                                        mnemonic: "BIT 3, A",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x60,
                                        mnemonic: "BIT 4, B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x61,
                                        mnemonic: "BIT 4, C",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x68,
                                        mnemonic: "BIT 5, B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x69,
                                        mnemonic: "BIT 5, C",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x6F,
                                        mnemonic: "BIT 5, A",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x70,
                                        mnemonic: "BIT 6, B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x77,
                                        mnemonic: "BIT 6, A",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x78,
                                        mnemonic: "BIT 7, B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x7C,
                                        mnemonic: "BIT 7, H",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x7E,
                                        mnemonic: "BIT 7, (HL)",
                                        length: 1,
                                        cycles: 16,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x7F,
                                        mnemonic: "BIT 7, A",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x86,
                                        mnemonic: "RES 0, (HL)",
                                        length: 1,
                                        cycles: 16,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0x87,
                                        mnemonic: "RES 0, A",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0xBE,
                                        mnemonic: "RES 7, (HL)",
                                        length: 1,
                                        cycles: 16,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0xD8,
                                        mnemonic: "SET 3, B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0xF8,
                                        mnemonic: "SET 7, B",
                                        length: 1,
                                        cycles: 8,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    },
                                    OpCode {
                                        code: 0xFE,
                                        mnemonic: "SET 7, (HL)",
                                        length: 1,
                                        cycles: 16,
                                        argument_type: ArgumentType::Implied,
                                        extended: true,
                                    }];
